### ISSUE TITLE
Design the architecture of the database documents

### ISSUE THREAD

**Issue by MacOSO** [blurtech/bookcrossing-backend#10]
* FireStore
* user document
* book document

**Comment by mittalchirag** [comment]
Is this to be done using MongoDB? Can you elaborate more about FireStone?

**Comment by MacOSO** [comment]
@mittalchirag Firestore is NoSQL Google Database from Firebase services.
Official doc: https://firebase.google.com/docs/firestore/

**Comment by MacOSO** [comment]
User - id, name, lastname, university, email, password, array of his books, array of wishlist
Book - owner id, array of properties (name, date of publishing, picture, description and etc), an array of those who want to book

**Comment by mittalchirag** [comment]
@MacOSO 
OK I'll take this issue. Please assign it to me. 
Thanks.
